# Generated by Django 5.0.6 on 2024-07-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField(max_length=10)),
                ('_class', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=10)),
            ],
        ),
    ]
